import initTabNav from "./modules/tabNav.js";
import initAccordion from "./modules/accordion.js";
import initScrollSuave from "./modules/scrollSuave.js";
import initAnimacaoScroll from "./modules/animacaoScroll.js";
import initModal from "./modules/modal.js";
import initToolTip from "./modules/tooltip.js";
import initDropDownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initTabNav();
initAccordion();
initScrollSuave();
initAnimacaoScroll();
initModal();
initToolTip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
